version: '3.7'
services:
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    container_name: sweepstake-redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redis_data:/data
  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: sweepstake-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    build:
      context: .
    depends_on:
      - redis
      - mysql
    restart: unless-stopped
    container_name: sweepstake-be
    command: sh -c "yarn start:prod"
    env_file:
      - .env.production.local
    tty: true
    ports:
      - "${PORT}:${PORT}"
volumes:
  redis_data:
  mysql_data:
