export enum EEnvKey {
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    HOST_ADDRESS = 'HOST_ADDRESS',

    // redis
    REDIS_HOST = 'REDIS_HOST',
    REDIS_PASSWORD = 'REDIS_PASSWORD',
    REDIS_PORT = 'REDIS_PORT',
    REDIS_DB_NUMBER = 'REDIS_DB_NUMBER',

    // mysql
    DB_TYPE = 'DB_TYPE',
    DB_HOST = 'DB_HOST',
    DB_PORT = 'DB_PORT',
    DB_USER = 'DB_USER',
    DB_PASSWORD = 'DB_PASSWORD',
    DB_DATABASE = 'DB_DATABASE',
    DB_MAX_QUERY_EXECUTION_TIME = 'DB_MAX_QUERY_EXECUTION_TIME',

    // kafka
    KAFKA_HOST = 'KAFKA_HOST',
    KAFKA_PORT = 'KAFKA_PORT',

    // swagger
    GLOBAL_PREFIX = 'GLOBAL_PREFIX',
    SWAGGER_PATH = 'SWAGGER_PATH',
    SWAGGER_IS_PUBLIC = 'SWAGGER_IS_PUBLIC',
    SWAGGER_HOST = 'SWAGGER_HOST',
    SWAGGER_VERSION = 'SWAGGER_VERSION',
    SWAGGER_TITLE = 'SWAGGER_TITLE',
    SWAGGER_DESC = 'SWAGGER_DESC',
    SWAGGER_USERNAME = 'SWAGGER_USERNAME',
    SWAGGER_PASSWORD = 'SWAGGER_PASSWORD',

    // logger
    IS_WRITE_LOG = 'IS_WRITE_LOG',
    LOG_LEVEL = 'LOG_LEVEL',

    // JWT
    JWT_SECRET = 'JWT_SECRET',
    JWT_EXPIRE = 'JWT_EXPIRE',
    JWT_SECRET_REFRESH = 'JWT_SECRET_REFRESH',
    JWT_EXPIRE_REFRESH = 'JWT_EXPIRE_REFRESH',

    RPC_URL = 'RPC_URL',
    GQL_URL = 'GQL_URL',

    ADMIN_PRIVATE_KEY = 'ADMIN_PRIVATE_KEY',
    SHINAMI_ACCESS_KEY = 'SHINAMI_ACCESS_KEY',

    SWEEPSTAKE_CONTRACT = 'SWEEPSTAKE_CONTRACT',
    CONDITIONAL_MARKET_CONTRACT = 'CONDITIONAL_MARKET_CONTRACT',

    // Config
    FEE_CREATE_MARKET = 'FEE_CREATE_MARKET',
}
